name: Build
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: selt-hosted
    steps:
      -  name: Checkout
         uses: actions/checkout@v3
      -  name: Install deps
         run: npm ci
      -  name: Build
         run: npm run build
      -  name: Start
         run: npm run start
