name: Deploy
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install deps
        run: npm ci
      - name: Lint
        run: npm run lint
  test:
    needs: [ lint ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install deps
        run: npm ci
      - name: Lint
        run: npm run test
  cleanup:
    needs: [ test ]
    runs-on: self-hosted
    steps:
      - name: Docker prune
        run: docker system prune -f
      - name: Stop current container
        run: docker stop ci_cd_test && docker rm ci_cd_test || echo "Запущенного контейнера нету"
  deploy:
    needs: [ cleanup ]
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create image
        run: docker build -t ci_cd_test .
      - name: Start container
        run: docker run --restart=always --name ci_cd_test -d -p 3000:3000 ci_cd_test
